### ISSUE TITLE
Version Key missing

### ISSUE THREAD

**Issue by ESPmonster** [danieldotnl/hass-multiscrape#7]
From the hassio logs:

> `No 'version' key in the manifest file for custom integration 'multiscrape'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'multiscrape`

**Comment by danieldotnl** [comment]
The version has been added to this component 2 months ago. Please upgrade or even better: switch to the new ha-multiscrape (https://github.com/danieldotnl/ha-multiscrape) component which is now part the default HACS store.

**Comment by ESPmonster** [comment]
Yea sorry for wasting your time, I wasn't paying attention properly. I actually use the fork of @drogfild (https://github.com/drogfild/hass-multiscrape) because it supports login but he hasn't upgraded yet with version number and there is no way to contact him/open an issue there... Frustrating! =(

**Comment by talonpoika** [comment]
Thanks @ESPmonster for reaching out. I now added Issues to my fork so you can use that also. You can also DM me at Home Assistant community. I'll try to add version key soon.

**Comment by ESPmonster** [comment]
@drogfild great, thanks a lot! BTW super happy with your code, I use it to scrape my solar power production

**Comment by danieldotnl** [comment]
In the meantime, you could just add manually: 
`"version": "1.0.0" `
to the manifest file in the multiscrape folder.

**Comment by talonpoika** [comment]
Thanks guys! I already updated my code to include version in manifest file. It's only change so you can update only it. Be sure to check also dev branch that is using async for network requests.
